добавил файлы повторно для проверки
Vladimir2308/react-otus-homework2 pull request #2
Opened 2021-11-12 07:19 UTC by Vladimir2308

ДЗ #2  
Добавлено поле Filed в виде классового компонента.  
Добавлены ячейки Item в виде функционального компонента без состояния.  
При нажатию на клетку выводится порядковый номер клетки, при повторном нажатии номер исчезает.  
Компоненты разработаны с использованием storybook, покрыты тестами, настроен loki.  

Для запуска приложения "npm start".  
Остановка приложения ctrl+C. 
Для запуска тестов "npm test".  
Для запуска storybook "npm run stotybook".  
Остановка storybook ctrl+C.

2021-11-12 10:48 UTC, vasiliev-alexey requested changes
1. Сконфигурировать  eslint -  в проекте много нарушений  стилей и типизации

/home/alex/tmp/react-otus-homework2/src/components/Field.test.tsx
  10:9  error  'elementsByClassName' is never reassigned. Use 'const' instead  prefer-const
  17:9  error  'elementsByClassName' is never reassigned. Use 'const' instead  prefer-const
  24:9  error  'elementsByClassName' is never reassigned. Use 'const' instead  prefer-const

/home/alex/tmp/react-otus-homework2/src/components/Field.tsx
  21:24  warning  Missing return type on function                     @typescript-eslint/explicit-module-boundary-types
  33:3   warning  Missing return type on function                     @typescript-eslint/explicit-module-boundary-types
  34:9   error    'members' is never reassigned. Use 'const' instead  prefer-const
  36:9   error    'rows' is never reassigned. Use 'const' instead     prefer-const
  43:38  error    Don't use `Number` as a type. Use number instead    @typescript-eslint/ban-types
  43:60  error    Don't use `Number` as a type. Use number instead    @typescript-eslint/ban-types

2. Зачем в проекте файл webpack.config2.js

3. В секции scripts - слишком много не нужных сценариев

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Item.tsx
> +      id={"" + props.order_num}
Странная конструкция

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Item.tsx
> +  onclickItemToField: any;
от  any надо избавлятсья

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Item.tsx
> +interface Props {
Обычно в имена пропсов формируюися КомпонентПропс

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Item.test.tsx
> +    expect(cell.textContent === "888");
заиспользовать матчеры  toBe  toEqual

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Field.tsx
> +    let members = getMembers(this.props.horiz_count, this.props.vertic_count);
Почитать про деструктуризацию пропсов https://ru.hackit-ukraine.com/1357-learn-the-basics-of-destructuring-props-in-react

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Field.tsx
> +interface IState {
Стандартный нейминг КомпонетСтейт

2021-11-12 10:48 UTC, vasiliev-alexey commented on src/components/Field.tsx
> +    if (Number(this.state.display_num) === id) {
судя по типу стейта он и так число, зачем явный каст ?

2021-11-12 14:30 UTC, Vladimir2308 commented on src/components/Item.tsx
> +      id={"" + props.order_num}
Пишут что это лучший способ преобразования числа в строку
https://stackoverflow.com/questions/5765398/whats-the-best-way-to-convert-a-number-to-a-string-in-javascript

2021-11-12 15:00 UTC, Vladimir2308 commented
> 
> 
>     1. Сконфигурировать  eslint -  в проекте много нарушений  стилей и типизации
> 
> 
> /home/alex/tmp/react-otus-homework2/src/components/Field.test.tsx 10:9 error 'elementsByClassName' is never reassigned. Use 'const' instead prefer-const 17:9 error 'elementsByClassName' is never reassigned. Use 'const' instead prefer-const 24:9 error 'elementsByClassName' is never reassigned. Use 'const' instead prefer-const
> 
> /home/alex/tmp/react-otus-homework2/src/components/Field.tsx 21:24 warning Missing return type on function @typescript-eslint/explicit-module-boundary-types 33:3 warning Missing return type on function @typescript-eslint/explicit-module-boundary-types 34:9 error 'members' is never reassigned. Use 'const' instead prefer-const 36:9 error 'rows' is never reassigned. Use 'const' instead prefer-const 43:38 error Don't use `Number` as a type. Use number instead @typescript-eslint/ban-types 43:60 error Don't use `Number` as a type. Use number instead @typescript-eslint/ban-types
> 
>     1. Зачем в проекте файл webpack.config2.js
> 
>     2. В секции scripts - слишком много не нужных сценариев

2021-11-12 15:00 UTC, closed without merging

2021-11-12 15:00 UTC, Vladimir2308 commented on src/components/Field.tsx
> +    if (Number(this.state.display_num) === id) {
Убрал

2021-11-12 15:01 UTC, Vladimir2308 commented on src/components/Item.tsx
> +  onclickItemToField: any;
Исправил

2021-11-12 15:01 UTC, Vladimir2308 commented on src/components/Item.tsx
> +interface Props {
Исправил

2021-11-12 15:01 UTC, Vladimir2308 commented on src/components/Item.test.tsx
> +    expect(cell.textContent === "888");
Исправил

2021-11-12 15:01 UTC, Vladimir2308 commented on src/components/Field.tsx
> +    let members = getMembers(this.props.horiz_count, this.props.vertic_count);
Исправил

2021-11-12 15:01 UTC, Vladimir2308 commented on src/components/Field.tsx
> +interface IState {
Исправил

2021-11-12 15:02 UTC, Vladimir2308 commented
eslint сконфигурировал, лишние файлы и скрипты удалил

2021-11-16 16:19 UTC, Vladimir2308 commented
Исправления в https://github.com/Vladimir2308/react-otus-homework2/pull/3

2021-11-22 13:51 UTC, sfuid commented on src/components/Field.tsx
> +    function getMembers(horiz_count: number, vertic_count: number) {
Вынести метод из render в тело класса